import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Calvin from '../components/Calvin'
import Votr from '../components/Votr'
import CnC from '../components/CnC'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Will Andrée innit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Wmicon.png" />
      </Head>

      <main className={styles.main}>
        <div className='bigdiv'>
          <h1 className="name">
            Will<br />
            Andrée
          </h1>
          <div className='pron'>[pron. wil on-dray]</div>
          <div className='descripsh'>
            <div className="barkport">
              barkley portfolio
            </div>
            Mr. Collins, meanwhile, was meditating in solitude on what had passed. He thought too well of himself to comprehend on what motives his cousin could refuse him; and though his pride was hurt, he suffered in no other way. His regard for her was quite imaginary; and the possibility of her deserving her mother’s reproach prevented his feeling any regret.
            While the family were in this confusion, Charlotte Lucas came to spend the day with them. She was met in the vestibule by Lydia, who, flying to her, cried in a half whisper, “I am glad you are come, for there is such fun here! What do you think has happened this morning? Mr. Collins has made an offer to Lizzy, and she will not have him.”
            <div className='descripsh descripsh--2'>
              <div className="detailsContainer">
                <div className='skillsContainer subcontainer'>
                  <h3 className="bskillz">
                    skillz
                  </h3>
                  <ul>
                    <li>Graphic Design</li>
                    <li>User Experience Design</li>
                    <li>Trend Forecasting</li>
                    <li>Logo Design</li>
                    <li>JavaScript</li>
                    <li>React Web Development <br /><span style={{ paddingLeft: "10px" }}>(and some Express/Node/API Development to boot)</span></li>
                    <li>Wordpress Development</li>
                  </ul>
                </div>
                <div className='businessContainer subcontainer'>
                  <h3 className="bskillz">
                    business
                  </h3>
                  <ul>
                    <li><a href="/resume" target="_blank">Resumé</a></li>
                    <li><a href="https://www.linkedin.com/in/william-andree/" target="_blank">LinkedIn</a></li>
                    <li><a href="mailto:williamandree@gmail.com">williamandree@gmail.com</a></li>
                    <li><a href="tel:5738202616">(573) 820-2616</a></li>
                  </ul>
                  <h3 className="bskillz" style={{marginBlockStart: "1rem"}}>
                    favorite designers
                  </h3>
                  <ul>
                    <li><a href="http://tmthyl.uk/" target="_blank">Timothy Luke</a></li>
                    <li><a href="https://www.instagram.com/d_a_n_i_e_l_s_w_a_n/" target="_blank">Daniel Swan</a></li>

                  </ul>
                </div>
                <div className='skillsContainer subcontainer'>
                  <h3 className="bskillz">
                    Fonts I ❤
                  </h3>
                  <ul>
                    <li className='roobert'>Roobert</li>
                    <li className='america'>GT America</li>
                    <li className='skelter'>Skelter</li>
                    <li className='forma'>Forma</li>
                  </ul>
                </div>
              </div>
            </div>
            <div className='guiderails'></div>
          </div>

        </div>
        <section className='bottomdiv'>
          <Calvin />
          <br />
          <br />
          <br />
          <br />
          <CnC />
          <br />
          <br />
          <br />
          <br />
          <Votr />
          <br />
          <br />
          <br />
          <br />
        </section>
        <div className='fontsContainer subcontainer'>
          <h3 className="bskillz">
            favorite fonts at the moment
          </h3>
          <ul>
            <li><img className="font" src="/SkelterFont.png" /></li>
          </ul>
        </div>
      </main>
    </div>
  )
}
